# Generated by Django 4.1.7 on 2023-05-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, default='img/avata.jpg', null=True, upload_to='images/'),
        ),
    ]
