# Generated by Django 4.1.7 on 2023-04-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='type',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='status',
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('Coffee', 'Coffee'), ('Milk_Tea', 'Milk_Tea'), ('Refreshments', 'Refreshments')], max_length=50),
        ),
    ]
