# Generated by Django 4.1.7 on 2023-05-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Phục Vụ', 'Phục Vụ'), ('Bưng Bê', 'Bưng Bê'), ('Pha Bhế', 'Pha Bhế')], default='Phục Vụ', max_length=50),
        ),
    ]
