# Generated by Django 4.1.7 on 2023-04-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_remove_cart_employee_remove_cart_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('Coffee', 'Coffee'), ('Milk_Tea', 'Milk_Tea'), ('Cake', 'Cake')], max_length=50),
        ),
    ]
