# Generated by Django 4.1.7 on 2023-04-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='type',
            field=models.CharField(choices=[('ordering', 'ordering'), ('delivery', 'delivery')], default='ordering', max_length=50),
        ),
    ]
