# Generated by Django 4.1.7 on 2023-04-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_cart_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='type',
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('ordering', 'ordering'), ('delivery', 'delivery'), ('received', 'received')], default='ordering', max_length=50),
        ),
    ]
